export  const ADD_RIDDLE_REQUEST = "ADD_RIDDLE_REQUEST";
export  const ADD_RIDDLE_SUCCESS = "ADD_RIDDLE_SUCCESS";
export  const ADD_RIDDLE_FALIURE = "ADD_RIDDLE_FALIURE";

export  const DELETE_RIDDLE_REQUEST = "ADD_RIDDLE_REQUEST";
export  const DELETE_RIDDLE_SUCCESS = "ADD_RIDDLE_SUCCESS";
export  const DELETE_RIDDLE_FALIURE = "ADD_RIDDLE_FALIURE";

export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FALIURE = "GET_DATA_FALIURE";
