export  const ADD_RIDDLE_REQUEST = "ADD_RIDDLE_REQUEST";
export  const ADD_RIDDLE_SUCCESS = "ADD_RIDDLE_SUCCESS";
export  const ADD_RIDDLE_FALIURE = "ADD_RIDDLE_FALIURE";

export  const DELETE_RIDDLE_REQUEST = "ADD_RIDDLE_REQUEST";
export  const DELETE_RIDDLE_SUCCESS = "ADD_RIDDLE_SUCCESS";
export  const DELETE_RIDDLE_FALIURE = "ADD_RIDDLE_FALIURE";


